wandb: attention_testing
name: trl2d-fano-dirpool-8x8pat
stage_name: stage1

vars:
  # Training hyperparameters (same as baseline)
  lr: 5.0e-5
  batch_size: 4
  max_batch_size: 4
  epochs: 500
  version: v1
  
  # Model dimensions
  model_dim: 256  # TRL2D uses 256 (vs zpinch 192)
  num_latent_tokens: 256
  
  # FANO-specific parameters
  encoder_type: fano
  num_fano_layers: 2  # Start with 2, try 4 if underfitting
  fano_num_heads: 8   # More heads for higher dim (256/8 = 32 per head)
  fourier_modes: 9    # Fourier modes per dimension
  
  # Patching configuration - TRL2D grid (verified via utils/check_trl2d_dimensions.py)
  grid_h: 128
  grid_w: 384
  num_patches_h: 8   # 128 / 8 = 16 (patch height)
  num_patches_w: 24  # 384 / 24 = 16 (patch width)
  patch_pooling_type: spatial_avg
  
  # Disable graph-based components for pure FANO
  radius_graph_r: null
  radius_graph_max_num_neighbors: null
  num_supernodes: null
  num_input_points: null
  num_query_points: null
  
  # Rollout settings
  rollout_num_input_points: 49152  # Full TRL2D mesh
  norm: mean0std1
  clamp: 0
  clamp_mode: log
  max_num_timesteps: 101

  optim:
    kind: lion
    lr: ${vars.lr}
    weight_decay: 0.5
    schedule:
      template: ${yaml:schedules/wupcos_epoch_}
      template.vars.end_epoch: 10

datasets:
  train:
    kind: well_trl2d_dataset
    split: train
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    num_input_points: ${vars.num_input_points}
    num_query_points: ${vars.num_query_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 72
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

  train_rollout:
    kind: well_trl2d_dataset
    split: train
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: .inf
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 72
    num_input_points: ${vars.rollout_num_input_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

  test_rollout:
    kind: well_trl2d_dataset
    split: test
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: .inf
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 9
    num_input_points: ${vars.rollout_num_input_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

  valid_rollout:
    kind: well_trl2d_dataset
    split: valid
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: .inf
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 9
    num_input_points: ${vars.rollout_num_input_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

  test:
    kind: well_trl2d_dataset
    split: test
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    num_input_points: ${vars.num_input_points}
    num_query_points: ${vars.num_query_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 9
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs:
      dim: ${vars.model_dim}
    optim: ${vars.optim}
  
  encoder:
    kind: encoders.cfd_fano_perceiver  # ← NEW FANO ENCODER
    num_latent_tokens: ${vars.num_latent_tokens}
    num_fano_layers: ${vars.num_fano_layers}
    kwargs:
      input_dim: 16  # 4 timesteps × 4 channels for TRL2D
      # Update input_dim if dataset configuration changes
      d_model: ${vars.model_dim}
      num_heads: ${vars.fano_num_heads}
      perc_dim: ${vars.model_dim}
      perc_num_heads: 4  # Perceiver cross-attention heads
      H: ${vars.grid_h}
      W: ${vars.grid_w}
      num_patches_h: ${vars.num_patches_h}
      num_patches_w: ${vars.num_patches_w}
      fourier_modes: ${vars.fourier_modes}
      pooling_type: ${vars.patch_pooling_type}
      dropout: 0.1
      activation: gelu
      dim_feedforward: 1024  # 4 × d_model
    optim: ${vars.optim}
  
  latent:
    kind: latent.transformer_model  # UNCHANGED
    depth: 4
    kwargs:
      dim: ${vars.model_dim}
      num_attn_heads: 4
      drop_path_rate: 0.0
      init_weights: xavier_uniform
    optim: ${vars.optim}
  
  decoder:
    kind: decoders.cfd_transformer_perceiver  # UNCHANGED
    depth: 4
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs:
      dim: ${vars.model_dim}
      perc_dim: 96
      num_attn_heads: 4
      perc_num_attn_heads: 2
      drop_path_rate: 0.0
      init_weights: xavier_uniform
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  early_stopper:
    kind: metric_early_stopper
    every_n_epochs: 1
    tolerance: 10
    metric_key: loss/online/x_hat/E1
  log_every_n_epochs: 1
  callbacks:
    - kind: best_checkpoint_callback
      every_n_epochs: 1
      metric_key: loss/online/x_hat/E1
      save_optim: true
    - kind: checkpoint_callback
      every_n_epochs: 100
      save_weights: false
      save_latest_weights: true
      save_latest_optim: true
    - kind: checkpoint_callback
      every_n_epochs: 100
      save_weights: true
      save_optim: true
    - kind: offline_correlation_time_callback
      every_n_epochs: 25
      dataset_key: train_rollout
    - kind: offline_correlation_time_callback
      every_n_epochs: 25
      dataset_key: test_rollout

