wandb: disabled
name: trl2d-ultra-aggressive-overfit
stage_name: stage1
vars:
  lr: 5.0e-3  # Moderate high LR
  batch_size: 1
  max_batch_size: 1
  epochs: 5000  # Many more epochs
  model_dim: 384
  num_latent_tokens: 1024  # Much more capacity
  num_supernodes: 2048
  radius_graph_r: 5.0
  radius_graph_max_num_neighbors: 32

  optim:
    kind: adam
    lr: ${vars.lr}
    weight_decay: 0.0
    lr_scaler:
      kind: linear_lr_scaler
      divisor: 1  # Disable LR scaling!

datasets:
  train:
    kind: well_trl2d_dataset
    split: train
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    norm: mean0std1
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 101
    max_num_sequences: 1
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs:
      dim: 384
    optim: ${vars.optim}
  encoder:
    kind: encoders.cfd_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 6  # Much deeper
    kwargs:
      gnn_dim: 192
      enc_dim: 192
      perc_dim: 384
      enc_num_attn_heads: 6
      perc_num_attn_heads: 6
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 6
    kwargs:
      dim: 384
      num_attn_heads: 6
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 6
    use_last_norm: false
    clamp: 0
    clamp_mode: log
    kwargs:
      dim: 384
      perc_dim: 192
      num_attn_heads: 6
      perc_num_attn_heads: 6
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 100
  callbacks:
    - kind: checkpoint_callback
      every_n_epochs: 1000
      save_weights: true
      save_optim: true

