wandb: disabled
name: trl2d-overfit-single-sample
stage_name: stage1
vars:
  lr: 1.0e-3  # Higher LR for faster overfitting
  batch_size: 1
  max_batch_size: 1
  epochs: 1000  # Many epochs to overfit
  version: v1
  model_dim: 128
  num_latent_tokens: 128
  num_input_points: null
  num_query_points: null
  num_supernodes: 1024
  radius_graph_r: 5.0
  radius_graph_max_num_neighbors: 32
  norm: mean0std1
  clamp: 0
  clamp_mode: log
  max_num_timesteps: 101

  optim:
    kind: adam  # Adam for debugging (more stable)
    lr: ${vars.lr}
    weight_decay: 0.0  # No regularization for overfitting

datasets:
  train:
    kind: well_trl2d_dataset
    split: train
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    num_input_points: ${vars.num_input_points}
    num_query_points: ${vars.num_query_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 1  # ONLY ONE SAMPLE
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

  test:
    kind: well_trl2d_dataset
    split: train  # Use same sample for test
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    num_input_points: ${vars.num_input_points}
    num_query_points: ${vars.num_query_points}
    norm: ${vars.norm}
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    max_num_timesteps: ${vars.max_num_timesteps}
    max_num_sequences: 1  # Same single sample
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs: ${select:dim192:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.cfd_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 2  # Smaller for faster training
    kwargs: ${select:dim96to192:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 2  # Smaller for faster training
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 2  # Smaller for faster training
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs: ${select:dim192to96:${yaml:models/decoders/transformer_perceiver}}
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 10
  callbacks:
    # Checkpoint frequently
    - kind: checkpoint_callback
      every_n_epochs: 100
      save_weights: true
      save_optim: true

