wandb: disabled
name: trl2d-timing-full
stage_name: stage1
vars:
  lr: 5.0e-5
  batch_size: 4
  max_batch_size: 4
  epochs: 2  # Run for 2 epochs to get better timing statistics
  version: v1
  model_dim: 256
  num_latent_tokens: 256
  num_input_points: null
  num_query_points: null
  num_supernodes: 2048
  radius_graph_r: 5.0
  radius_graph_max_num_neighbors: 32
  rollout_num_input_points: 49152
  norm: mean0std1
  clamp: 0
  clamp_mode: log
  max_num_timesteps: 101

  optim:
    kind: lion
    lr: ${vars.lr}
    weight_decay: 0.5
    schedule:
      template: ${yaml:schedules/wupcos_epoch_}
      template.vars.end_epoch: 10

datasets:
  train:
    kind: well_trl2d_dataset
    split: train
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    num_input_points: ${vars.num_input_points}
    num_query_points: ${vars.num_query_points}
    norm: mean0std1
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 101
    max_num_sequences: 16  # Use 16 sequences for better statistics
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs: ${select:dim192:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.cfd_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 4
    kwargs: ${select:dim96to192:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 4
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 4
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs: ${select:dim192to96:${yaml:models/decoders/transformer_perceiver}}
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 1
  callbacks: []



