wandb: UPT_benchmarking_well
name: trl2d-gaot-style-v2
stage_name: trl2d_gaot_style_v2
vars:
  lr: 8.0e-4
  batch_size: 12  # Match GAOT's batch size
  max_batch_size: 12
  epochs: 1000  # Match GAOT's epochs
  num_latent_tokens: 256  # Larger like GAOT (64x64 grid)
  num_supernodes: 2048
  radius_graph_r: 5.0
  radius_graph_max_num_neighbors: 32
  clamp: 0
  clamp_mode: log

  optim:
    kind: adamw  # Match GAOT
    lr: ${vars.lr}
    weight_decay: 1.0e-5  # Match GAOT
    schedule:
      - schedule:
          kind: linear_increasing_schedule
          exclude_first: true
          exclude_last: true
        end_epoch: 10
      - schedule:
          kind: cosine_decreasing_schedule
          exclude_last: true
        end_epoch: ${vars.epochs}

datasets:
  train:
    kind: well_trl2d_dataset
    split: train
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4  # Use 4 input timesteps like GAOT
    num_output_timesteps: 1  # Predict next timestep
    norm: mean0std1_auto
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 101
    max_num_sequences: 72  # Match GAOT's train_size
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

  test:
    kind: well_trl2d_dataset
    split: test
    well_base_path: /home/workspace/projects/data/datasets_david/datasets/
    num_input_timesteps: 4
    norm: mean0std1_auto
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 101
    max_num_sequences: 9  # Match GAOT's test_size
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs: ${select:dim192:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.cfd_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 4
    kwargs: ${select:dim96to192:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 4
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 4
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs: ${select:dim192to96:${yaml:models/decoders/transformer_perceiver}}
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 10
  callbacks: []  # Disable all default callbacks to avoid BestCheckpointCallback error

