wandb: cvsim
name: tgv2d-1sample-overfit
stage_name: stage1
vars:
  lr: 1.0e-3
  batch_size: 1
  max_batch_size: 1
  epochs: 200

  dataset:
    kind: lagrangian_dataset
    name: tgv2d
    n_input_timesteps: 3
    n_pushforward_timesteps: 9
    graph_mode: radius_graph_with_supernodes
    radius_graph_r: 0.1
    radius_graph_max_num_neighbors: 4
    n_supernodes: 128

  optim:
    kind: adamw
    lr: ${vars.lr}
    weight_decay: 0.0

datasets:
  train:
    kind: ${vars.dataset.kind}
    name: ${vars.dataset.name}
    split: train
    n_input_timesteps: ${vars.dataset.n_input_timesteps}
    n_pushforward_timesteps: ${vars.dataset.n_pushforward_timesteps}
    graph_mode: ${vars.dataset.graph_mode}
    radius_graph_r: ${vars.dataset.radius_graph_r}
    radius_graph_max_num_neighbors: ${vars.dataset.radius_graph_max_num_neighbors}
    n_supernodes: ${vars.dataset.n_supernodes}
    num_points_range: [ 1250, 2500 ]
    collators:
      - kind: lagrangian_simformer_collator
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1

  test:
    kind: ${vars.dataset.kind}
    name: ${vars.dataset.name}
    split: test
    test_mode: parts_traj
    n_input_timesteps: ${vars.dataset.n_input_timesteps}
    graph_mode: ${vars.dataset.graph_mode}
    radius_graph_r: ${vars.dataset.radius_graph_r}
    radius_graph_max_num_neighbors: ${vars.dataset.radius_graph_max_num_neighbors}
    n_supernodes: ${vars.dataset.n_supernodes}
    seed: 0
    collators:
      - kind: lagrangian_simformer_collator
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1

model:
  kind: lagrangian_simformer_model
  conditioner:
    kind: conditioners.timestep_conditioner_pdearena
    kwargs: ${select:tiny:${yaml:models/timestep_embed}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.lagrangian_pool_transformer_perceiver
    num_latent_tokens: 64
    enc_depth: 2
    kwargs: ${select:dim96to192:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 2
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.lagrangian_perceiver
    kwargs: ${select:dim192:${yaml:models/decoders/perceiver}}
    optim: ${vars.optim}

trainer:
  kind: lagrangian_large_t_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  forward_kwargs:
    reconstruct_prev_target: false
    encode_target: false
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 5
  callbacks:
    - kind: offline_loss_callback
      every_n_epochs: 10
      dataset_key: test
    - kind: checkpoint_callback
      every_n_epochs: 50
      save_weights: true
      save_optim: true


