wandb: newpt_logging
name: helmholtz_baseline
stage_name: helmholtz_lowbatch
stage_id: helmholtz_lowbatch_v1

vars:
  lr: 1.0e-3
  batch_size: 4  # Reduced from 4 to avoid OOM
  max_batch_size: 4
  epochs: 20
  num_latent_tokens: 256
  num_supernodes: 2048
  radius_graph_r: 5.0
  radius_graph_max_num_neighbors: 32
  clamp: 0
  clamp_mode: log

  optim:
    kind: adamw
    lr: ${vars.lr}
    weight_decay: 1.0e-5
    schedule:
      template: ${yaml:schedules/wupcos_epoch}
      template.vars.end_epoch: 10

datasets:
  train:
    kind: well_hs_dataset
    split: train
    num_input_timesteps: 4
    norm: mean0std1_auto
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 50
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}
  test:
    kind: well_hs_dataset
    split: test
    num_input_timesteps: 4
    norm: mean0std1_auto
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 50
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs: ${select:dim192:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.cfd_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 4
    kwargs: ${select:dim96to192:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 4
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 4
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs: ${select:dim192to96:${yaml:models/decoders/transformer_perceiver}}
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 1

  # timing/profiling (disabled by default; enable for Helmholtz tests only)
  timing:
    enabled: true
    sample_every_n_updates: 50
    sample_first_n_per_epoch: 3
    reduce: mean
    file_format: pkl


