wandb: helmholtz_quadtree_overfit
name: helmholtz-quadtree-overfit
stage_name: helmholtz_quadtree_overfit
vars:
  lr: 1.0e-3
  optim:
    kind: adam
    lr: ${vars.lr}
    betas: [0.9, 0.99]
  batch_size: 1
  max_batch_size: 1
  epochs: 1000
  model_dim: 192
  num_latent_tokens: 256
  num_supernodes: 4096
  max_children: 64
  aggregator: mlp

datasets:
  train:
    kind: well_hs_dataset
    split: train
    num_input_timesteps: 4
    num_output_timesteps: 1
    max_num_timesteps: 50
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1
    collators:
      - kind: zpinch_quadtree_collator
        num_supernodes: ${vars.num_supernodes}
        max_nodes_per_supernode: ${vars.max_children}
  valid:
    kind: well_hs_dataset
    split: valid
    num_input_timesteps: 4
    num_output_timesteps: 1
    max_num_timesteps: 50
    max_num_sequences: 1
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1
    collators:
      - kind: zpinch_quadtree_collator
        num_supernodes: ${vars.num_supernodes}
        max_nodes_per_supernode: ${vars.max_children}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs: ${select:dim192:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.quadtree_encoder
    optim: ${vars.optim}
    dim: ${vars.model_dim}
    aggregator: ${vars.aggregator}
    subnode_feature_dim: 2
    supernode_feature_dim: 2
    max_children: ${vars.max_children}
    expected_stat_dim: 2
    aggregator_kwargs:
      hidden_dim: 256
      num_layers: 2
      activation: gelu
  latent:
    kind: latent.transformer_model
    optim: ${vars.optim}
    depth: 4
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    optim: ${vars.optim}
    depth: 4
    use_last_norm: true
    kwargs: ${select:dim192to96:${yaml:models/decoders/transformer_perceiver}}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  detach_reconstructions: true
  reconstruct_prev_x_weight: 0.0
  reconstruct_dynamics_weight: 0.0
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss

