name: Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  pytest:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # Test min and max supported Python versions
          python-version:
            - "3.10"
            - "3.13"
      steps:
        - uses: actions/checkout@v4
        - uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install the_well
          run: uv sync --all-extras --dev
        - name: Run tests
          env:
            PY_COLORS: "1"
          run: uv run pytest tests
