wandb: disabled
name: zpinch-64x64-overfit
stage_name: zpinch_64_overfit
vars:
  lr: 1.0e-3
  batch_size: 1
  max_batch_size: 1
  epochs: 100
  model_dim: 192
  num_latent_tokens: 256
  num_supernodes: 2048
  radius_graph_r: 5.0
  radius_graph_max_num_neighbors: 32
  clamp: 0
  clamp_mode: log
  optim:
    kind: adam
    lr: ${vars.lr}
    weight_decay: 0.0
    lr_scaler:
      kind: linear_lr_scaler
      divisor: 1


datasets:
  train:
    kind: well_zpinch_dataset
    split: train
    root: /home/workspace/flash/ZEN_WELL_train/64x64/data/
    num_input_timesteps: 4
    norm: mean0std1_auto
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    max_num_timesteps: 202
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1

  valid:
    kind: well_zpinch_dataset
    split: valid
    root: /home/workspace/flash/ZEN_WELL_train/64x64/data/
    num_input_timesteps: 4
    norm: mean0std1_auto
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    max_num_timesteps: 202
    max_num_sequences: 1
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1
    collators:
      - kind: cfd_simformer_collator
        num_supernodes: ${vars.num_supernodes}

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs: ${select:dim192:${yaml:models/dim}}
    optim: ${vars.optim}
  encoder:
    kind: encoders.cfd_pool_transformer_perceiver
    num_latent_tokens: ${vars.num_latent_tokens}
    enc_depth: 2
    kwargs: ${select:dim96to192:${yaml:models/encoders/pool_transformer_perceiver}}
    optim: ${vars.optim}
  latent:
    kind: latent.transformer_model
    depth: 4
    kwargs: ${select:dim192:${yaml:models/latent/transformer}}
    optim: ${vars.optim}
  decoder:
    kind: decoders.cfd_transformer_perceiver
    depth: 2
    use_last_norm: true
    clamp: ${vars.clamp}
    clamp_mode: ${vars.clamp_mode}
    kwargs: ${select:dim192to96:${yaml:models/decoders/transformer_perceiver}}
    optim: ${vars.optim}

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  radius_graph_r: ${vars.radius_graph_r}
  radius_graph_max_num_neighbors: ${vars.radius_graph_max_num_neighbors}
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
  log_every_n_epochs: 1
  callbacks: []
