wandb: disabled
name: zpinch-quadtree-overfit
stage_name: zpinch_quadtree_overfit
vars:
  lr: 1.0e-3
  optim:
    kind: adam
    lr: ${vars.lr}
    weight_decay: 0.0
    lr_scaler:
      kind: linear_lr_scaler
      divisor: 1
  batch_size: 1
  max_batch_size: 1
  epochs: 1000
  model_dim: 192
  num_latent_tokens: 256
  num_supernodes: 2048
  max_children: 256
  aggregator: mlp
  root_path: /home/workspace/flash/ZEN_WELL_train/64x64/data/


datasets:
  train:
    kind: well_zpinch_dataset
    split: train
    root: ${vars.root_path}
    num_input_timesteps: 4
    num_output_timesteps: 1
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1
    collators:
      - kind: zpinch_quadtree_collator
        num_supernodes: ${vars.num_supernodes}
        max_nodes_per_supernode: ${vars.max_children}
    norm: mean0std1_auto
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 202
  valid:
    kind: well_zpinch_dataset
    split: valid
    root: ${vars.root_path}
    num_input_timesteps: 4
    num_output_timesteps: 1
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 1
    collators:
      - kind: zpinch_quadtree_collator
        num_supernodes: ${vars.num_supernodes}
        max_nodes_per_supernode: ${vars.max_children}
    norm: mean0std1_auto
    clamp: 0
    clamp_mode: log
    max_num_timesteps: 202

model:
  kind: cfd_simformer_model
  conditioner:
    kind: conditioners.timestep_velocity_conditioner_pdearena
    kwargs:
      dim: 192
    optim: ${vars.optim}
  encoder:
    kind: encoders.quadtree_encoder
    optim: ${vars.optim}
    dim: ${vars.model_dim}
    aggregator: ${vars.aggregator}
    subnode_feature_dim: 2
    supernode_feature_dim: 2
    max_children: ${vars.max_children}
    expected_stat_dim: 4
  latent:
    kind: latent.transformer_model
    optim: ${vars.optim}
    depth: 4
    kwargs:
      dim: 192
      num_attn_heads: 3
  decoder:
    kind: decoders.cfd_transformer_perceiver
    optim: ${vars.optim}
    depth: 4
    use_last_norm: true
    kwargs:
      dim: 192
      perc_dim: 96
      num_attn_heads: 3
      perc_num_attn_heads: 2

trainer:
  kind: cfd_simformer_trainer
  precision: float32
  max_epochs: ${vars.epochs}
  effective_batch_size: ${vars.batch_size}
  max_batch_size: ${vars.max_batch_size}
  detach_reconstructions: true
  reconstruct_prev_x_weight: 0.0
  reconstruct_dynamics_weight: 0.0
  loss_function:
    kind: elementwise_loss
    loss_function:
      kind: mse_loss
